// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQu1Tbvxc7bszuy30hDwN2Zao4SEMb4xQ',
    appId: '1:670967196705:web:3e5b34b6474a9e4797c760',
    messagingSenderId: '670967196705',
    projectId: 'synapse-fd0cd',
    authDomain: 'synapse-fd0cd.firebaseapp.com',
    storageBucket: 'synapse-fd0cd.firebasestorage.app',
    measurementId: 'G-RTPXTCN11Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDccDJlIWjGpifP1bEWyEHf7YVJdhpsl90',
    appId: '1:670967196705:android:947164645e6e674097c760',
    messagingSenderId: '670967196705',
    projectId: 'synapse-fd0cd',
    storageBucket: 'synapse-fd0cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgjz64hbqDpDammec7bDGXtWZWXGZhWE',
    appId: '1:670967196705:ios:e71331e00054b96797c760',
    messagingSenderId: '670967196705',
    projectId: 'synapse-fd0cd',
    storageBucket: 'synapse-fd0cd.firebasestorage.app',
    iosClientId: '670967196705-f0e5b2riglk4pukna4rjktvrlgagb7ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgjz64hbqDpDammec7bDGXtWZWXGZhWE',
    appId: '1:670967196705:ios:e71331e00054b96797c760',
    messagingSenderId: '670967196705',
    projectId: 'synapse-fd0cd',
    storageBucket: 'synapse-fd0cd.firebasestorage.app',
    iosClientId: '670967196705-f0e5b2riglk4pukna4rjktvrlgagb7ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQu1Tbvxc7bszuy30hDwN2Zao4SEMb4xQ',
    appId: '1:670967196705:web:a1cadc595227c46297c760',
    messagingSenderId: '670967196705',
    projectId: 'synapse-fd0cd',
    authDomain: 'synapse-fd0cd.firebaseapp.com',
    storageBucket: 'synapse-fd0cd.firebasestorage.app',
    measurementId: 'G-NZ7MGG49CY',
  );
}
